### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/vqa2/raw/annotations/mscoco_train2014_annotations.json'

### ISSUE THREAD

**Issue by jancen0** [Cadene/vqa.pytorch#49]
After installing the dependencies and starting the server, a script is trying to download resources resulting in a 404.

--2019-12-11 20:14:09--  http://visualqa.org/data/mscoco/vqa/v2_Questions_Train_mscoco.zip
Auflösen des Hostnamens visualqa.org (visualqa.org)… 185.199.109.153, 185.199.110.153, 185.199.108.153, ...
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.109.153|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://visualqa.org/data/mscoco/vqa/v2_Questions_Train_mscoco.zip [folgend]
--2019-12-11 20:14:09--  https://visualqa.org/data/mscoco/vqa/v2_Questions_Train_mscoco.zip
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.109.153|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2019-12-11 20:14:09 FEHLER 404: Not Found.

--2019-12-11 20:14:09--  http://visualqa.org/data/mscoco/vqa/v2_Questions_Val_mscoco.zip
Auflösen des Hostnamens visualqa.org (visualqa.org)… 185.199.110.153, 185.199.108.153, 185.199.111.153, ...
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.110.153|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://visualqa.org/data/mscoco/vqa/v2_Questions_Val_mscoco.zip [folgend]
--2019-12-11 20:14:09--  https://visualqa.org/data/mscoco/vqa/v2_Questions_Val_mscoco.zip
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.110.153|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2019-12-11 20:14:10 FEHLER 404: Not Found.

--2019-12-11 20:14:10--  http://visualqa.org/data/mscoco/vqa/v2_Questions_Test_mscoco.zip
Auflösen des Hostnamens visualqa.org (visualqa.org)… 185.199.108.153, 185.199.111.153, 185.199.109.153, ...
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.108.153|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://visualqa.org/data/mscoco/vqa/v2_Questions_Test_mscoco.zip [folgend]
--2019-12-11 20:14:10--  https://visualqa.org/data/mscoco/vqa/v2_Questions_Test_mscoco.zip
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.108.153|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2019-12-11 20:14:10 FEHLER 404: Not Found.

--2019-12-11 20:14:10--  http://visualqa.org/data/mscoco/vqa/v2_Annotations_Train_mscoco.zip
Auflösen des Hostnamens visualqa.org (visualqa.org)… 185.199.111.153, 185.199.109.153, 185.199.110.153, ...
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.111.153|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://visualqa.org/data/mscoco/vqa/v2_Annotations_Train_mscoco.zip [folgend]
--2019-12-11 20:14:10--  https://visualqa.org/data/mscoco/vqa/v2_Annotations_Train_mscoco.zip
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.111.153|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2019-12-11 20:14:10 FEHLER 404: Not Found.

--2019-12-11 20:14:10--  http://visualqa.org/data/mscoco/vqa/v2_Annotations_Val_mscoco.zip
Auflösen des Hostnamens visualqa.org (visualqa.org)… 185.199.109.153, 185.199.110.153, 185.199.108.153, ...
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.109.153|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://visualqa.org/data/mscoco/vqa/v2_Annotations_Val_mscoco.zip [folgend]
--2019-12-11 20:14:11--  https://visualqa.org/data/mscoco/vqa/v2_Annotations_Val_mscoco.zip
Verbindungsaufbau zu visualqa.org (visualqa.org)|185.199.109.153|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2019-12-11 20:14:11 FEHLER 404: Not Found.

unzip:  cannot find or open data/vqa2/raw/zip/v2_Questions_Train_mscoco.zip, data/vqa2/raw/zip/v2_Questions_Train_mscoco.zip.zip or data/vqa2/raw/zip/v2_Questions_Train_mscoco.zip.ZIP.
unzip:  cannot find or open data/vqa2/raw/zip/v2_Questions_Val_mscoco.zip, data/vqa2/raw/zip/v2_Questions_Val_mscoco.zip.zip or data/vqa2/raw/zip/v2_Questions_Val_mscoco.zip.ZIP.
unzip:  cannot find or open data/vqa2/raw/zip/v2_Questions_Test_mscoco.zip, data/vqa2/raw/zip/v2_Questions_Test_mscoco.zip.zip or data/vqa2/raw/zip/v2_Questions_Test_mscoco.zip.ZIP.
unzip:  cannot find or open data/vqa2/raw/zip/v2_Annotations_Train_mscoco.zip, data/vqa2/raw/zip/v2_Annotations_Train_mscoco.zip.zip or data/vqa2/raw/zip/v2_Annotations_Train_mscoco.zip.ZIP.
unzip:  cannot find or open data/vqa2/raw/zip/v2_Annotations_Val_mscoco.zip, data/vqa2/raw/zip/v2_Annotations_Val_mscoco.zip.zip or data/vqa2/raw/zip/v2_Annotations_Val_mscoco.zip.ZIP.
mv: rename data/vqa2/raw/annotations/v2_mscoco_train2014_annotations.json to data/vqa2/raw/annotations/mscoco_train2014_annotations.json: No such file or directory
mv: rename data/vqa2/raw/annotations/v2_mscoco_val2014_annotations.json to data/vqa2/raw/annotations/mscoco_val2014_annotations.json: No such file or directory
mv: rename data/vqa2/raw/annotations/v2_OpenEnded_mscoco_train2014_questions.json to data/vqa2/raw/annotations/OpenEnded_mscoco_train2014_questions.json: No such file or directory
mv: rename data/vqa2/raw/annotations/v2_OpenEnded_mscoco_val2014_questions.json to data/vqa2/raw/annotations/OpenEnded_mscoco_val2014_questions.json: No such file or directory
mv: rename data/vqa2/raw/annotations/v2_OpenEnded_mscoco_test2015_questions.json to data/vqa2/raw/annotations/OpenEnded_mscoco_test2015_questions.json: No such file or directory
mv: rename data/vqa2/raw/annotations/v2_OpenEnded_mscoco_test-dev2015_questions.json to data/vqa2/raw/annotations/OpenEnded_mscoco_test-dev2015_questions.json: No such file or directory
Loading annotations and questions...
Traceback (most recent call last):
  File "demo_server.py", line 174, in <module>
    main()
  File "demo_server.py", line 144, in main
    options['vqa'])
  File "/Users/xxxxxx/vqa.pytorch/vqa/datasets/vqa.py", line 258, in factory
    dataset_vqa = VQA2(data_split, opt, dataset_img)
  File "/Users/xxxxxx/vqa.pytorch/vqa/datasets/vqa.py", line 148, in __init__
    super(VQA2, self).__init__(data_split, opt, dataset_img)
  File "/Users/xxxxxx/vqa.pytorch/vqa/datasets/vqa.py", line 21, in __init__
    super(AbstractVQA, self).__init__(data_split, opt, dataset_img)
  File "/Users/xxxxxx/vqa.pytorch/vqa/datasets/utils.py", line 20, in __init__
    self._interim()
  File "/Users/xxxxxx/vqa.pytorch/vqa/datasets/vqa.py", line 179, in _interim
    vqa2_interim(self.opt['dir'])
  File "/Users/xxxxxx/vqa.pytorch/vqa/datasets/vqa2_interim.py", line 52, in vqa_interim
    annotations_train = json.load(open(os.path.join(dir_vqa, 'raw', 'annotations', 'mscoco_train2014_annotations.json'), 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/vqa2/raw/annotations/mscoco_train2014_annotations.json'

I would be very happy if you could take a look on this issue, since I'm very eager to try out your pre-trained models, thanks in advance!

**Comment by jancen0** [comment]
I'm currently fixing the issue, it was caused by outdated links. I'll make a Pull request when I'm done :)
